import { createParser } from "../utils";

export const DIR_ALIASES: Record<string, string> = {
  n: "north",
  north: "north",
  s: "south",
  south: "south",
  e: "east",
  east: "east",
  w: "west",
  west: "west",
  forward: "north",
  fwd: "north",
  back: "south",
};

const VERB_ALIASES: Record<string, string> = {
  look: "look",
  l: "look",
  examine: "look",
  x: "look",
  inspect: "look",
  read: "look",
  take: "take",
  get: "take",
  grab: "take",
  pick: "take",
  drop: "drop",
  use: "use",
  open: "open",
  activate: "activate",
  reroute: "reroute",
  restore: "reroute",
  connect: "reroute",
  fix: "reroute",
  launch: "launch",
  enter: "enter",
  go: "move",
  walk: "move",
  run: "move",
  move: "move",
  head: "move",
  crawl: "move",
  inventory: "inv",
  inv: "inv",
  i: "inv",
  help: "help",
  "?": "help",
  wait: "wait",
  z: "wait",
  yell: "yell",
  scream: "yell",
  shout: "yell",
  quit: "quit",
  restart: "restart",
  reset: "restart",
  leave: "leave",
  exit: "leave",
};

export const parse = createParser(DIR_ALIASES, VERB_ALIASES);
